version: '3.1'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.ps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hypersku
    ports:
      - "5051:5051"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs-app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile.web
    environment:
      - DATABASE_URL="postgresql://root:root@db:5051/hypersku?connect_timeout=300"
    ports:
      - "3000:3000"
    restart: always

volumes:
  pgdata:
