import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const categories = [
  "Women's Clothing",
  "Men's Clothing",
  "Pet Supplies",
  "Mother/Kids/Baby",
  "Toys Hobbies",
  "Fashion Jewelry",
  "Shoes",
  "Luggage Bags",
  "Furniture",
  "Lights Lighting",
];

const products = [
  {
    name: "Women Trouser",
    description: "A silky women trouser",
    price: 13.23,
    categoryName: "Women's Clothing",
    subCategory: "Bottom Wears",
    rating: 4.5,
  },
  {
    name: "Women Jacket",
    description: "A silky women jacket",
    price: 20.56,
    categoryName: "Women's Clothing",
    subCategory: "Top Wears",
    rating: 3,
  },
  {
    name: "Women Blouse",
    description: "A silky women blouse",
    price: 15.23,
    categoryName: "Women's Clothing",
    subCategory: "Top Wears",
    rating: 4.5,
  },
  {
    name: "Women Dress",
    description: "A beautiful summer dress",
    price: 24.3,
    categoryName: "Women's Clothing",
    subCategory: "Dresses",
    rating: 4.0,
  },
  {
    name: "Women Skirt",
    description: "A pencil skirt for work",
    price: 17.99,
    categoryName: "Women's Clothing",
    subCategory: "Bottom Wears",
    rating: 4.5,
  },
  {
    name: "Women Sweater",
    description: "A warm women's sweater for winter",
    price: 40.0,
    categoryName: "Women's Clothing",
    subCategory: "Top Wears",
    rating: 4.8,
  },
  {
    name: "Women Jeans",
    description: "A pair of high-waisted jeans for women",
    price: 45.0,
    categoryName: "Women's Clothing",
    subCategory: "Bottom Wears",
    rating: 4.6,
  },
  {
    name: "Women Swimwear",
    description: "A fashionable one-piece swimwear for women",
    price: 30.0,
    categoryName: "Women's Clothing",
    subCategory: "Swimwears",
    rating: 4.5,
  },
  {
    name: "Men Jacket",
    description: "A sport jacket for men",
    price: 25.23,
    categoryName: "Men's Clothing",
    subCategory: "Top Wears",
    rating: 4.5,
  },
  {
    name: "Men Trouser",
    description: "A sport trouser for men",
    price: 18.23,
    categoryName: "Men's Clothing",
    subCategory: "Bottom Wears",
    rating: 5,
  },
  {
    name: "Men T-Shirt",
    description: "A casual T-Shirt for men",
    price: 10.0,
    categoryName: "Men's Clothing",
    subCategory: "Top Wears",
    rating: 4.5,
  },
  {
    name: "Men Suit",
    description: "A formal suit for men",
    price: 120.5,
    categoryName: "Men's Clothing",
    subCategory: "Dress Suit",
    rating: 4.7,
  },
  {
    name: "Men Sweater",
    description: "A warm men's sweater for winter",
    price: 45.0,
    categoryName: "Men's Clothing",
    subCategory: "Top Wears",
    rating: 4.6,
  },
  {
    name: "Men Jeans",
    description: "A pair of straight-leg jeans for men",
    price: 50.0,
    categoryName: "Men's Clothing",
    subCategory: "Casual Jeans",
    rating: 4.8,
  },
  {
    name: "Men Swimwear",
    description: "Stylish swim shorts for men",
    price: 25.0,
    categoryName: "Men's Clothing",
    subCategory: "Swimwear",
    rating: 4.4,
  },
  {
    name: "Cat Litter Box",
    description: "A covered cat litter box",
    price: 40.0,
    categoryName: "Pet Supplies",
    subCategory: "Cat Litter Boxes",
    rating: 4.6,
  },
  {
    name: "Dog Leash",
    description: "A durable dog leash",
    price: 15.0,
    categoryName: "Pet Supplies",
    subCategory: "Dog Collars & Leashes",
    rating: 4.8,
  },
  {
    name: "Fish Tank",
    description: "A large fish tank with filtration",
    price: 80.0,
    categoryName: "Pet Supplies",
    subCategory: "Aquariums",
    rating: 4.7,
  },
  {
    name: "Bird Cage",
    description: "A spacious bird cage",
    price: 60.0,
    categoryName: "Pet Supplies",
    subCategory: "Bird Cages",
    rating: 4.5,
  },
  {
    name: "Baby Stroller",
    description: "A lightweight baby stroller",
    price: 100.0,
    categoryName: "Mother/Kids/Baby",
    subCategory: "Strollers",
    rating: 4.6,
  },
  {
    name: "Kids Toys",
    description: "A variety of fun kids toys",
    price: 30.0,
    categoryName: "Toys Hobbies",
    subCategory: "Educational Toys",
    rating: 4.7,
  },
  {
    name: "Hobby Kits",
    description: "DIY hobby kits for kids and adults",
    price: 25.0,
    categoryName: "Toys Hobbies",
    subCategory: "DIY Kits",
    rating: 4.8,
  },
  {
    name: "Diamond Earrings",
    description: "Elegant diamond earrings",
    price: 300.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Earrings",
    rating: 4.9,
  },
  {
    name: "Gold Necklace",
    description: "A luxurious gold necklace",
    price: 500.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Necklaces",
    rating: 4.8,
  },
  {
    name: "Women's Sandals",
    description: "Comfortable sandals for women",
    price: 40.0,
    categoryName: "Shoes",
    subCategory: "Women's Sandals",
    rating: 4.5,
  },
  {
    name: "Men's Boots",
    description: "Sturdy boots for men",
    price: 80.0,
    categoryName: "Shoes",
    subCategory: "Men's Boots",
    rating: 4.6,
  },
  {
    name: "Travel Bag",
    description: "A durable travel bag",
    price: 70.0,
    categoryName: "Luggage Bags",
    subCategory: "Travel Bags",
    rating: 4.7,
  },
  {
    name: "Handbag",
    description: "A fashionable handbag for women",
    price: 60.0,
    categoryName: "Luggage Bags",
    subCategory: "Handbags",
    rating: 4.5,
  },
  {
    name: "Wooden Sofa",
    description: "Sofa made from acacia wood",
    price: 150.23,
    categoryName: "Furniture",
    subCategory: "Sofas",
    rating: 3,
  },
  {
    name: "Dining Table",
    description: "A large dining table for family meals",
    price: 250.0,
    categoryName: "Furniture",
    subCategory: "Dining Tables",
    rating: 4.5,
  },
  {
    name: "Floor Lamp",
    description: "A stylish floor lamp",
    price: 70.0,
    categoryName: "Lights Lighting",
    subCategory: "Floor Lamps",
    rating: 4.6,
  },
  {
    name: "Table Lamp",
    description: "A convenient table lamp",
    price: 30.0,
    categoryName: "Lights Lighting",
    subCategory: "Table Lamps",
    rating: 4.5,
  },
  {
    name: "Chandelier",
    description: "An elegant chandelier for a living room",
    price: 200.0,
    categoryName: "Lights Lighting",
    subCategory: "Chandeliers",
    rating: 4.7,
  },
  {
    name: "Wall Light",
    description: "A decorative wall light",
    price: 50.0,
    categoryName: "Lights Lighting",
    subCategory: "Wall Lights",
    rating: 4.5,
  },
  {
    name: "Outdoor Light",
    description: "A durable outdoor light for your garden",
    price: 60.0,
    categoryName: "Lights Lighting",
    subCategory: "Outdoor Lighting",
    rating: 4.6,
  },
  {
    name: "Kids Bed",
    description: "A comfortable and safe bed for kids",
    price: 120.0,
    categoryName: "Furniture",
    subCategory: "Kids Furniture",
    rating: 4.8,
  },
  {
    name: "Office Chair",
    description: "An ergonomic office chair",
    price: 90.0,
    categoryName: "Furniture",
    subCategory: "Office Furniture",
    rating: 4.6,
  },
  {
    name: "Bookcase",
    description: "A spacious bookcase for your books",
    price: 75.0,
    categoryName: "Furniture",
    subCategory: "Shelving",
    rating: 4.7,
  },
  {
    name: "Coffee Table",
    description: "A stylish coffee table",
    price: 80.0,
    categoryName: "Furniture",
    subCategory: "Tables",
    rating: 4.6,
  },
  {
    name: "Backpack",
    description: "A practical backpack for everyday use",
    price: 40.0,
    categoryName: "Luggage Bags",
    subCategory: "Backpacks",
    rating: 4.7,
  },
  {
    name: "Briefcase",
    description: "A professional briefcase for work",
    price: 80.0,
    categoryName: "Luggage Bags",
    subCategory: "Briefcases",
    rating: 4.6,
  },
  {
    name: "Suitcase",
    description: "A large suitcase for travel",
    price: 100.0,
    categoryName: "Luggage Bags",
    subCategory: "Suitcases",
    rating: 4.7,
  },
  {
    name: "Kids Shoes",
    description: "Comfortable and durable shoes for kids",
    price: 30.0,
    categoryName: "Shoes",
    subCategory: "Kids' Shoes",
    rating: 4.6,
  },
  {
    name: "Running Shoes",
    description: "Shoes suitable for running and sports",
    price: 50.0,
    categoryName: "Shoes",
    subCategory: "Sports Shoes",
    rating: 4.7,
  },
  {
    name: "High Heels",
    description: "Elegant high heels for special occasions",
    price: 60.0,
    categoryName: "Shoes",
    subCategory: "Women's Heels",
    rating: 4.5,
  },
  {
    name: "Bracelet",
    description: "A beautiful bracelet as an accessory",
    price: 100.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Bracelets",
    rating: 4.6,
  },
  {
    name: "Ring",
    description: "A stylish ring to complement your look",
    price: 150.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Rings",
    rating: 4.7,
  },
  {
    name: "Watch",
    description: "A trendy watch for men and women",
    price: 200.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Watches",
    rating: 4.6,
  },
  {
    name: "Board Games",
    description: "Fun board games for the whole family",
    price: 30.0,
    categoryName: "Toys Hobbies",
    subCategory: "Board Games",
    rating: 4.8,
  },
  {
    name: "Puzzle",
    description: "A challenging puzzle for kids",
    price: 20.0,
    categoryName: "Toys Hobbies",
    subCategory: "Puzzles",
    rating: 4.7,
  },
  {
    name: "Dolls",
    description: "Cute dolls for kids",
    price: 25.0,
    categoryName: "Toys Hobbies",
    subCategory: "Dolls",
    rating: 4.6,
  },
  {
    name: "Action Figures",
    description: "Action figures from popular movies and comics",
    price: 35.0,
    categoryName: "Toys Hobbies",
    subCategory: "Action Figures",
    rating: 4.7,
  },
  {
    name: "Stroller",
    description: "A comfortable stroller for your baby",
    price: 150.0,
    categoryName: "Mother/Kids/Baby",
    subCategory: "Strollers",
    rating: 4.8,
  },
  {
    name: "Baby Monitor",
    description: "A digital baby monitor with camera",
    price: 120.0,
    categoryName: "Mother/Kids/Baby",
    subCategory: "Baby Monitors",
    rating: 4.9,
  },
  {
    name: "Maternity Dress",
    description: "A comfortable and stylish maternity dress",
    price: 50.0,
    categoryName: "Mother/Kids/Baby",
    subCategory: "Maternity Clothes",
    rating: 4.8,
  },
  {
    name: "Kids Toys",
    description: "Educational toys for kids",
    price: 30.0,
    categoryName: "Mother/Kids/Baby",
    subCategory: "Toys",
    rating: 4.7,
  },
  {
    name: "Diapers",
    description: "Absorbent diapers for your baby",
    price: 35.0,
    categoryName: "Mother/Kids/Baby",
    subCategory: "Diapers",
    rating: 4.8,
  },
  {
    name: "Dog Food",
    description: "Nutritious dog food for your pet",
    price: 40.0,
    categoryName: "Pet Supplies",
    subCategory: "Dog Food",
    rating: 4.8,
  },
  {
    name: "Cat Scratcher",
    description: "A cat scratcher to keep your pet entertained",
    price: 25.0,
    categoryName: "Pet Supplies",
    subCategory: "Cat Furniture",
    rating: 4.6,
  },
  {
    name: "Bird Cage",
    description: "A spacious bird cage for your feathered friend",
    price: 90.0,
    categoryName: "Pet Supplies",
    subCategory: "Bird Supplies",
    rating: 4.7,
  },
  {
    name: "Fish Tank",
    description: "A beautiful fish tank for your aquatic pets",
    price: 120.0,
    categoryName: "Pet Supplies",
    subCategory: "Aquariums",
    rating: 4.8,
  },
  {
    name: "Dog Bed",
    description: "A comfortable bed for your dog",
    price: 60.0,
    categoryName: "Pet Supplies",
    subCategory: "Dog Beds",
    rating: 4.8,
  },
  {
    name: "Men's Boots",
    description: "Stylish and comfortable boots for men",
    price: 80.0,
    categoryName: "Shoes",
    subCategory: "Men's Boots",
    rating: 4.7,
  },
  {
    name: "Women's Sneakers",
    description: "Trendy sneakers for women",
    price: 65.0,
    categoryName: "Shoes",
    subCategory: "Women's Sneakers",
    rating: 4.7,
  },
  {
    name: "Kids Sandals",
    description: "Comfortable sandals for kids",
    price: 25.0,
    categoryName: "Shoes",
    subCategory: "Kids' Sandals",
    rating: 4.6,
  },
  {
    name: "Men's Belt",
    description: "A genuine leather belt for men",
    price: 30.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Belts",
    rating: 4.7,
  },
  {
    name: "Women's Hat",
    description: "A stylish hat for women",
    price: 20.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Hats",
    rating: 4.7,
  },
  {
    name: "Necklace",
    description: "A beautiful necklace as a perfect gift",
    price: 150.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Necklaces",
    rating: 4.8,
  },
  {
    name: "Earrings",
    description: "Trendy earrings for a night out",
    price: 50.0,
    categoryName: "Fashion Jewelry",
    subCategory: "Earrings",
    rating: 4.6,
  },
  {
    name: "Toy Cars",
    description: "Fun toy cars for kids",
    price: 20.0,
    categoryName: "Toys Hobbies",
    subCategory: "Toy Cars",
    rating: 4.7,
  },
  {
    name: "RC Helicopter",
    description: "A remote control helicopter for outdoor fun",
    price: 75.0,
    categoryName: "Toys Hobbies",
    subCategory: "Remote Control Toys",
    rating: 4.8,
  },
  {
    name: "Stuffed Animals",
    description: "Soft and cuddly stuffed animals for kids",
    price: 25.0,
    categoryName: "Toys Hobbies",
    subCategory: "Stuffed Animals",
    rating: 4.9,
  },
  {
    name: "Puzzle Game",
    description: "Fun and educational puzzle game for children",
    price: 15.0,
    categoryName: "Toys Hobbies",
    subCategory: "Board Games",
    rating: 4.7,
  },
  {
    name: "Leather Backpack",
    description: "Stylish and durable leather backpack",
    price: 90.0,
    categoryName: "Luggage Bags",
    subCategory: "Backpacks",
    rating: 4.8,
  },
  {
    name: "Travel Suitcase",
    description: "Large suitcase for all your travel needs",
    price: 130.0,
    categoryName: "Luggage Bags",
    subCategory: "Suitcases",
    rating: 4.8,
  },
  {
    name: "Cosmetic Bag",
    description: "Compact cosmetic bag for all your beauty products",
    price: 20.0,
    categoryName: "Luggage Bags",
    subCategory: "Cosmetic Bags",
    rating: 4.6,
  },
  {
    name: "Camping Bag",
    description: "Durable camping bag for outdoor adventures",
    price: 80.0,
    categoryName: "Luggage Bags",
    subCategory: "Outdoor Bags",
    rating: 4.9,
  },
  {
    name: "Office Desk",
    description: "Spacious and sturdy office desk",
    price: 250.0,
    categoryName: "Furniture",
    subCategory: "Desks",
    rating: 4.8,
  },
  {
    name: "Coffee Table",
    description: "Modern coffee table for your living room",
    price: 150.0,
    categoryName: "Furniture",
    subCategory: "Tables",
    rating: 4.8,
  },
  {
    name: "Dining Chair",
    description: "Comfortable dining chair with cushion",
    price: 75.0,
    categoryName: "Furniture",
    subCategory: "Chairs",
    rating: 4.7,
  },
  {
    name: "Bookshelf",
    description: "Large bookshelf for your collection",
    price: 200.0,
    categoryName: "Furniture",
    subCategory: "Shelves",
    rating: 4.9,
  },
  {
    name: "Bed Frame",
    description: "Sturdy and stylish bed frame",
    price: 300.0,
    categoryName: "Furniture",
    subCategory: "Beds",
    rating: 4.8,
  },
  {
    name: "LED Bulb",
    description: "Energy efficient LED bulb",
    price: 10.0,
    categoryName: "Lights Lighting",
    subCategory: "Bulbs",
    rating: 4.7,
  },
  {
    name: "Table Lamp",
    description: "Modern table lamp for your bedside",
    price: 45.0,
    categoryName: "Lights Lighting",
    subCategory: "Lamps",
    rating: 4.7,
  },
  {
    name: "Chandelier",
    description: "Elegant chandelier for your dining room",
    price: 200.0,
    categoryName: "Lights Lighting",
    subCategory: "Ceiling Lights",
    rating: 4.8,
  },
  {
    name: "Outdoor Lights",
    description: "Solar powered outdoor lights for your garden",
    price: 50.0,
    categoryName: "Lights Lighting",
    subCategory: "Outdoor Lighting",
    rating: 4.9,
  },
  {
    name: "Fairy Lights",
    description: "Beautiful fairy lights for decoration",
    price: 15.0,
    categoryName: "Lights Lighting",
    subCategory: "String Lights",
    rating: 4.8,
  },
  {
    name: "Wall Sconce",
    description: "Wall sconce with a vintage design",
    price: 60.0,
    categoryName: "Lights Lighting",
    subCategory: "Wall Lights",
    rating: 4.7,
  },
  {
    name: "Kids Shoes",
    description: "Comfortable and durable shoes for kids",
    price: 30.0,
    categoryName: "Shoes",
    subCategory: "Kids Shoes",
    rating: 4.8,
  },
];

async function main() {
  const categoryTransaction = [];
  for (const category of categories) {
    categoryTransaction.push(
      prisma.category.create({
        data: {
          name: category,
        },
      })
    );
  }
  await prisma.$transaction(categoryTransaction);

  const productTransaction = [];

  for (const product of products) {
    const deliveryTime = Math.floor(Math.random() * 21) + 1;
    productTransaction.push(
      prisma.product.create({
        data: {
          name: product.name,
          description: product.description,
          price: product.price.toString(),
          deliveryTime: deliveryTime.toString(),
          rating: product.rating,
          category: {
            connect: {
              name: product.categoryName,
            },
          },
          subCategory: {
            connectOrCreate: {
              where: {
                name: product.subCategory,
              },
              create: {
                name: product.subCategory,
                parentCategory: {
                  connect: {
                    name: product.categoryName,
                  },
                },
              },
            },
          },
        },
      })
    );
  }

  await prisma.$transaction(productTransaction);
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
